create table permission
(
    id              bigint auto_increment comment '权限ID'
        primary key,
    parent_id       bigint   default 0                 null comment '父权限ID',
    permission_code varchar(255)                       not null comment '权限编码',
    permission_name varchar(50)                        not null comment '权限名称',
    permission_type tinyint                            not null comment '权限类型：1-菜单，2-按钮，3-接口',
    path            varchar(255)                       null comment '路由路径',
    component       varchar(255)                       null comment '组件路径',
    icon            varchar(50)                        null comment '图标',
    sort_order      int      default 0                 null comment '排序',
    status          tinyint  default 1                 null comment '状态：0-禁用，1-启用',
    deleted         tinyint  default 0                 null comment '是否删除：0-未删除，1-已删除',
    create_time     datetime default CURRENT_TIMESTAMP null comment '创建时间',
    update_time     datetime default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP comment '更新时间',
    create_by       bigint                             null comment '创建者',
    update_by       bigint                             null comment '更新者',
    constraint uk_permission_code
        unique (permission_code)
)
    comment '权限表' row_format = DYNAMIC;

create index idx_parent_id
    on permission (parent_id);

create index idx_permission_type
    on permission (permission_type);

create index idx_sort_order
    on permission (sort_order);

create index idx_status
    on permission (status);

INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (1, 0, 'DASHBOARD', '仪表盘', 1, '/dashboard', 'views/dashboard/index.vue', 'HomeFilled', 0, 1, 0, '2026-05-06 13:15:09', '2026-05-06 13:15:09', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (2, 0, 'USER.LIST', '用户管理', 1, '/user', 'views/user/index.vue', 'User', 1, 1, 0, '2026-05-06 13:15:09', '2026-05-06 13:15:09', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (3, 2, 'USER.ADD', '新增用户', 2, null, null, null, 0, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (4, 2, 'USER.EDIT', '编辑用户', 2, null, null, null, 1, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (5, 2, 'USER.DELETE', '删除用户', 2, null, null, null, 2, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (6, 0, 'ROLE.LIST', '角色管理', 1, '/role', 'views/role/index.vue', 'UserFilled', 2, 1, 0, '2026-05-06 13:15:09', '2026-05-06 13:15:09', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (7, 6, 'ROLE.ADD', '新增角色', 2, null, null, null, 0, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (8, 6, 'ROLE.EDIT', '编辑角色', 2, null, null, null, 1, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (9, 6, 'ROLE.DELETE', '删除角色', 2, null, null, null, 2, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (10, 6, 'ROLE.ASSIGN', '分配权限', 2, null, null, null, 3, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (11, 0, 'PERMISSION.LIST', '权限管理', 1, '/permission', 'views/permission/index.vue', 'Lock', 3, 1, 0, '2026-05-06 13:15:09', '2026-05-06 13:15:09', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (12, 11, 'PERMISSION.ADD', '新增权限', 2, null, null, null, 0, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (13, 11, 'PERMISSION.EDIT', '编辑权限', 2, null, null, null, 1, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (14, 11, 'PERMISSION.DELETE', '删除权限', 2, null, null, null, 2, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (15, 0, 'PROBLEM.LIST', '题目管理', 1, '/problem', 'views/problem/index.vue', 'Document', 4, 1, 0, '2026-05-06 13:15:09', '2026-05-06 13:15:09', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (16, 15, 'PROBLEM.ADD', '新增题目', 2, null, null, null, 0, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (17, 15, 'PROBLEM.EDIT', '编辑题目', 2, null, null, null, 1, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (18, 15, 'PROBLEM.DELETE', '删除题目', 2, null, null, null, 2, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (19, 15, 'TESTCASE.LIST', '查看测试用例', 2, null, null, null, 3, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (20, 15, 'TESTCASE.ADD', '新增测试用例', 2, null, null, null, 4, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (21, 15, 'TESTCASE.EDIT', '编辑测试用例', 2, null, null, null, 5, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (22, 15, 'TESTCASE.DELETE', '删除测试用例', 2, null, null, null, 6, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (23, 0, 'PROBLEM_SET.LIST', '题单管理', 1, '/problem-set', 'views/problemSet/index.vue', 'Collection', 5, 1, 0, '2026-05-06 13:15:09', '2026-05-06 13:15:09', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (24, 0, 'CONTEST.LIST', '竞赛管理', 1, '/contest', 'views/contest/index.vue', 'Trophy', 6, 1, 0, '2026-05-06 13:15:09', '2026-05-06 13:15:09', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (25, 0, 'LANGUAGE.LIST', '语言管理', 1, '/language', 'views/language/index.vue', 'Setting', 7, 1, 0, '2026-05-06 13:15:09', '2026-05-06 13:15:09', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (26, 25, 'LANGUAGE.ADD', '新增语言', 2, null, null, null, 0, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (27, 25, 'LANGUAGE.EDIT', '编辑语言', 2, null, null, null, 1, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (28, 25, 'LANGUAGE.DELETE', '删除语言', 2, null, null, null, 2, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (29, 0, 'BLOG.LIST', '博客管理', 1, '/blog', 'views/blog/index.vue', 'EditPen', 8, 1, 0, '2026-05-06 13:15:09', '2026-05-06 13:15:09', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (30, 29, 'BLOG.ADD', '新增博客', 2, null, null, null, 0, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (31, 29, 'BLOG.EDIT', '编辑博客', 2, null, null, null, 1, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (32, 29, 'BLOG.DELETE', '删除博客', 2, null, null, null, 2, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (33, 29, 'BLOG.TAG.LIST', '标签列表', 2, null, null, null, 3, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (34, 29, 'BLOG.TAG.ADD', '新增标签', 2, null, null, null, 4, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (35, 29, 'BLOG.TAG.EDIT', '编辑标签', 2, null, null, null, 5, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (36, 29, 'BLOG.TAG.DELETE', '删除标签', 2, null, null, null, 6, 1, 0, '2026-05-06 13:18:54', '2026-05-06 13:18:54', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (37, 0, 'SUBMISSION.LIST', '判题管理', 1, '/submission', 'views/submission/index.vue', 'List', 9, 1, 0, '2026-05-06 13:18:48', '2026-05-06 13:18:48', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (38, 0, 'CONTEST', 'Contest Management', 1, '/contest', 'contest/index', 'trophy', 40, 1, 0, '2026-05-06 12:48:31', '2026-05-06 13:18:43', null, null);
INSERT INTO emiya_oj_auth.permission (id, parent_id, permission_code, permission_name, permission_type, path, component, icon, sort_order, status, deleted, create_time, update_time, create_by, update_by) VALUES (39, 0, 'BLOG_MODERATION_MANAGE', 'Blog Moderation Manage', 3, '/blog/moderation/**', null, null, 41, 1, 0, '2026-05-06 12:48:31', '2026-05-06 13:18:43', null, null);
